twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        path_image_figure: '\images\figures'
        path_image_profil: '\images\profils'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
